# Install the pipenv environment and run tests

name: Pipenv install and run tests

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: lint
        run: |
          pip install --user .[dev]
          tox -e pre-commit,mypy