# Install the pipenv environment and run tests

name: Pipenv install and run tests

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: lint
        run: |
          pip install --user .[dev]
          tox -e pre-commit,mypy

  wheel:
    strategy:
      fail-fast: false

    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Create Sdist and Wheel
        # Set SOURCE_DATE_EPOCH from git commit for reproducible build
        # https://reproducible-builds.org/
        run: |
          SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) pipx run build --sdist --wheel
      - name: Upload Wheel and Sdist as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: Install minimum python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install wheel in a venv and check cli works
        # ${GITHUB_REPOSITORY##*/} is the repo name without org
        # Replace this with the cli command if different to the repo name
        run: pipx run --python $(which python3.8) --spec dist/*.whl ${GITHUB_REPOSITORY##*/} --help
  
  test:
    strategy:
      fail-fast: false

    runs-on: "ubuntu-latest"
    env:
      # https://github.com/pytest-dev/pytest/issues/2042
      PY_IGNORE_IMPORTMISMATCH: "1"
      # enable QT tests with no X Display
      QT_QPA_PLATFORM: "offscreen"

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: run tests
        run: |
          touch requirements_dev.txt
          pip install -e .[dev]
          pytest tests